version: '2.4'
x-loki: &loki
  logging:
    driver: loki
    options:
      loki-url: http://127.0.0.1:3100/loki/api/v1/push
services:
  loki:
    image: grafana/loki:1.5.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-local-config.yaml:/etc/loki/loki-local-config.yaml
      - ./loki/local_bind_volume_dir:/data/loki
  grafana:
    <<: *loki
    image: grafana/grafana:7.0.3
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning
    depends_on: 
      - loki
  app:
    <<: *loki
    image: alpine:latest
    entrypoint: ping host.docker.internal
    depends_on: 
      - loki