version: '3.8'
x-loki: &loki
  networks:
     - monitor
  logging:
    driver: loki
    options:
      loki-url: http://127.0.0.1:3100/loki/api/v1/push
services:
  loki:
    image: grafana/loki:1.5.0
    # container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    configs:
      - source: loki
        target: /etc/loki/loki-local-config.yaml
    volumes:
      - ./loki/local_bind_volume_dir:/data/loki
  grafana:
    <<: *loki
    image: grafana/grafana:7.0.3
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning
    depends_on: 
      - loki
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  cadvisor:
    <<: *loki
    image: google/cadvisor
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  node-exporter:
    <<: *loki
    image: prom/node-exporter:v1.0.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  prometheus:
    <<: *loki
    image: prom/prometheus:v2.19.0
    configs: 
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus:/prometheus
    ports:
      - "9090:9090"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M
configs:
  prometheus:
    file: ./prometheus/prometheus.yml
  loki:
    file: ./loki/loki-local-config.yaml
volumes:
  prometheus:
networks:
  monitor:
    name: monitor
    driver: overlay
    attachable: true
    config:
    - subnet: 172.28.0.0/16