global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - 'localhost:9090'
  - job_name: 'dockerd-exporter'
    static_configs:
    - targets: 
      - 'localhost:9323'
  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
  - job_name: 'tasks.cadvisor'
    dns_sd_configs:
    - names:
      - 'cadvisor'
      type: 'A'
      port: 8080