apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090/
    orgId: 1
    isDefault: false
    version: 1
    editable: false